version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=calendar_user
      - POSTGRES_PASSWORD=calendar_password
      - POSTGRES_DB=calendar
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U calendar_user -d calendar" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: