// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartAt              *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Event) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Event) GetStartAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartAt
	}
	return nil
}

func (m *Event) GetEndAt() *timestamppb.Timestamp {
	if m != nil {
		return m.EndAt
	}
	return nil
}

type EventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsRequest) Reset()         { *m = EventsRequest{} }
func (m *EventsRequest) String() string { return proto.CompactTextString(m) }
func (*EventsRequest) ProtoMessage()    {}
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsRequest.Unmarshal(m, b)
}
func (m *EventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsRequest.Marshal(b, m, deterministic)
}
func (m *EventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsRequest.Merge(m, src)
}
func (m *EventsRequest) XXX_Size() int {
	return xxx_messageInfo_EventsRequest.Size(m)
}
func (m *EventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventsRequest proto.InternalMessageInfo

type EventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

type EventsResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventsResponse) Reset()         { *m = EventsResponse{} }
func (m *EventsResponse) String() string { return proto.CompactTextString(m) }
func (*EventsResponse) ProtoMessage()    {}
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *EventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventsResponse.Unmarshal(m, b)
}
func (m *EventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventsResponse.Marshal(b, m, deterministic)
}
func (m *EventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventsResponse.Merge(m, src)
}
func (m *EventsResponse) XXX_Size() int {
	return xxx_messageInfo_EventsResponse.Size(m)
}
func (m *EventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventsResponse proto.InternalMessageInfo

func (m *EventsResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "proto.Event")
	proto.RegisterType((*EventsRequest)(nil), "proto.EventsRequest")
	proto.RegisterType((*EventResponse)(nil), "proto.EventResponse")
	proto.RegisterType((*EventsResponse)(nil), "proto.EventsResponse")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xbb, 0xa9, 0x69, 0xcc, 0xa4, 0x56, 0x58, 0x2a, 0x84, 0x5c, 0x0c, 0xc1, 0x43, 0x0e,
	0xb2, 0xc5, 0x14, 0x3d, 0x78, 0x6b, 0xad, 0x88, 0xd7, 0xa0, 0x17, 0x2f, 0x12, 0xc9, 0x58, 0x02,
	0x69, 0x12, 0xb3, 0x53, 0xc1, 0xbf, 0xe1, 0xc5, 0xbf, 0x2b, 0xd9, 0xed, 0x22, 0xe9, 0x45, 0x7a,
	0x1a, 0xe6, 0xe5, 0x7d, 0xf3, 0xc2, 0x63, 0xc1, 0xc3, 0x4f, 0xac, 0x48, 0x34, 0x6d, 0x4d, 0x35,
	0xb7, 0xd5, 0x08, 0xce, 0xd7, 0x75, 0xbd, 0x2e, 0x71, 0xa6, 0xb6, 0xb7, 0xed, 0xfb, 0x8c, 0x8a,
	0x0d, 0x4a, 0xca, 0x36, 0x8d, 0xf6, 0x45, 0x3f, 0x0c, 0xec, 0xfb, 0x8e, 0xe3, 0x13, 0xb0, 0x8a,
	0xdc, 0x67, 0x21, 0x8b, 0x87, 0xa9, 0x55, 0xe4, 0x7c, 0x0a, 0x36, 0x15, 0x54, 0xa2, 0x6f, 0x85,
	0x2c, 0x76, 0x53, 0xbd, 0xf0, 0x6b, 0x38, 0x96, 0x94, 0xb5, 0xf4, 0x9a, 0x91, 0x3f, 0x0c, 0x59,
	0xec, 0x25, 0x81, 0xd0, 0x19, 0xc2, 0x64, 0x88, 0x27, 0x93, 0x91, 0x3a, 0xca, 0xbb, 0x20, 0x7e,
	0x05, 0x23, 0xac, 0xf2, 0x0e, 0x3a, 0xfa, 0x17, 0xb2, 0xb1, 0xca, 0x17, 0x14, 0x9d, 0xc2, 0x89,
	0xfa, 0x31, 0x99, 0xe2, 0xc7, 0x16, 0xe5, 0x9f, 0x90, 0xa2, 0x6c, 0xea, 0x4a, 0x62, 0x74, 0x03,
	0x13, 0xe3, 0xd0, 0x0a, 0xbf, 0x80, 0x91, 0x2a, 0x41, 0xfa, 0x2c, 0x1c, 0xc6, 0x5e, 0x32, 0xd6,
	0xf7, 0x85, 0xe6, 0x76, 0xdf, 0x92, 0x6f, 0x0b, 0x1c, 0xa5, 0x60, 0xcb, 0xe7, 0xe0, 0xdd, 0xb5,
	0x98, 0x11, 0xea, 0x12, 0x7a, 0x40, 0x30, 0xed, 0xe1, 0x26, 0x76, 0xd0, 0x41, 0xcf, 0x4d, 0x7e,
	0x38, 0xb4, 0xc2, 0x12, 0x0f, 0x83, 0x2e, 0x61, 0xfc, 0x80, 0xa4, 0xd4, 0xe5, 0xd7, 0xe3, 0x6a,
	0x8f, 0xea, 0x6d, 0xd1, 0x80, 0xdf, 0x82, 0x6b, 0xdc, 0x92, 0xf7, 0x4e, 0x9a, 0x12, 0x83, 0xb3,
	0x3d, 0xd5, 0x24, 0x2d, 0xdd, 0x17, 0x47, 0xec, 0x9e, 0xc9, 0x48, 0x8d, 0xf9, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9e, 0x01, 0x89, 0xcb, 0x51, 0x02, 0x00, 0x00,
}
