basePath: /api/v1
definitions:
  http.Event:
    properties:
      end_at:
        description: The date and time of a event ended
        example: "2006-01-02T15:04:05.000Z"
        format: date-time
        type: string
      id:
        description: The unique identificator of a event
        example: 10
        type: integer
      start_at:
        description: The date and time of a event started
        example: "2006-01-02T15:04:05.000Z"
        format: date-time
        type: string
      title:
        description: The title of a event
        example: Webinar Getting Started with Swagger
        type: string
    type: object
info:
  contact: {}
  description: App Calendar server REST API.
  title: Calendar API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/http.Event'
            type: array
        "500":
          description: Unable to get events
          schema:
            type: string
      summary: Gett all events
      tags:
      - Event
    post:
      consumes:
      - application/json
      parameters:
      - description: Title
        in: query
        name: title
        required: true
        type: string
      - description: StartAt
        format: dateTime
        in: query
        name: start_at
        required: true
        type: string
      - description: EndAt
        format: dateTime
        in: query
        name: end_at
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create event
      tags:
      - Event
    put:
      consumes:
      - application/json
      parameters:
      - description: Id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: not found
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Delete event
      tags:
      - Event
swagger: "2.0"
